sudo: false
language: go
go:
  - 1.8.x
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go get -u github.com/golang/lint/golint
  - golint -set_exit_status . ./examples/...
  - golint ./elem/... event/... prop/... storeutil/... # TODO(slimsag): address these linter errors
  - go test -v -race ./...
